packages:
#  urls:
#    - https://atom.io/download/rpm
#    - https://download.01.org/gfx/fedora/25/noarch/intellinuxgraphics-repo-2.0.4-25.intel20164.noarch.rpm
#    - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-26.noarch.rpm
#    - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-26.noarch.rpm
  names:
    - ansible
    - mc
    - screen
    - the_silver_searcher
    - tig
    - tmux
    - vim

installed_users:
  - aries

internal_user:
  name: 'aries'
  uid: 1000
  group: 'aries'
  gid: 1000
#  password: "{{ buildbot_password }}"

ssh_key_location: "/home/{{ internal_user.name }}/.ssh/authorized_keys"

