---
- name: Ansible Playbook for laptop configuration
  hosts: laptop
  roles:
    - { role: aries1980.laptop-wsl, become: yes }
    - aries1980.k9s
    - role: geerlingguy.dotfiles
      when: install_dotfiles
    - role: gantsign.kops
    - andrewrothstein.kubectl
    - andrewrothstein.terraform
